export const GET_ADMIN_COURSES = 'GET_ADMIN_COURSES';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const PUBLISHED_COURSES = 'PUBLISHED_COURSES';
export const GET_USER_COURSES = 'GET_USER_COURSES';
